media:
  input: images
  output: /images

content:
  - name: site
    label: 店舗情報
    type: file
    path: data/site.json

    fields:
      - name: shopName
        label: 店名
        type: string

      - name: address
        label: 住所
        type: string

      - name: open
        label: 営業時間
        type: string

      - name: closed
        label: 定休日
        type: string

  - name: menu
    label: メニュー
    type: file
    path: data/menu.json

    fields:
      - name: categories
        label: メニューカテゴリ
        type: object
        list: true

        fields:
          - name: name
            label: カテゴリ名
            type: string

          - name: items
            label: 商品
            type: object
            list: true

            fields:
              - name: name
                label: 商品名
                type: string

              - name: price
                label: 価格
                type: string

              - name: description
                label: 説明文
                type: text
